package cli

import (
	"context"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chmmou/kasapi-cli/internal/api"
	"github.com/chmmou/kasapi-cli/internal/database"
)

// NewDatabasesCmd returns the "kasapi-cli databases" subcommand tree:
// list/get (get_databases, list and singular) plus the add / update /
// delete write endpoints (add_database / update_database /
// delete_database). update and delete are gated by the #109
// confirmation prompt; add is reversible and not prompted.
//
// delete_database drops the database and all data it holds — the
// confirmation prompt uses the verb "permanently delete" so the user
// sees that the action is data-loss, not just metadata removal.
func NewDatabasesCmd(opts *RootOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "databases",
		Short: "Inspect and manage databases (get/add/update/delete_database)",
	}
	cmd.AddCommand(
		newDatabasesListCmd(opts),
		newDatabasesGetCmd(opts),
		newDatabasesAddCmd(opts),
		newDatabasesUpdateCmd(opts),
		newDatabasesDeleteCmd(opts),
	)
	return cmd
}

func newDatabasesListCmd(opts *RootOptions) *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List all databases (get_databases, no filter)",
		Args:  cobra.NoArgs,
		RunE: runListE(opts, "get_databases", func(c *api.Client, ctx context.Context) (database.DatabaseList, error) {
			return database.NewClient(c).List(ctx)
		}),
	}
}

func newDatabasesGetCmd(opts *RootOptions) *cobra.Command {
	return &cobra.Command{
		Use:   "get <database-login>",
		Short: "Show details for a single database (get_databases with database_login)",
		Args:  cobra.ExactArgs(1),
		RunE: runGetE(opts, "get_databases", func(c *api.Client, ctx context.Context, arg string) (database.Database, error) {
			return database.NewClient(c).Get(ctx, arg)
		}),
	}
}

// databaseAddFlags binds the add_database request fields. add and
// update bind disjoint flag sets (same wire-key surface, but the help
// text of each subcommand reflects only its own action semantics, and
// cobra rejects a wrong-subcommand flag at parse time rather than
// silently ignoring it). The password flag maps to database_password
// (database_password is the add-only key; update has its own
// --password flag that maps to database_new_password — see
// databaseUpdateFlags).
type databaseAddFlags struct {
	password     string
	comment      string
	allowedHosts string
}

func (f *databaseAddFlags) bind(cmd *cobra.Command) {
	fl := cmd.Flags()
	fl.StringVar(&f.password, "password", "", "initial database password (required)")
	fl.StringVar(&f.comment, "comment", "", "human-readable comment / label for the new database (required)")
	fl.StringVar(&f.allowedHosts, "allowed-hosts", "", "comma-separated list of hosts allowed to connect (optional; an empty value is the KAS API's documented \"any host may connect\" wildcard, e.g. \"localhost, 192.168.100.10, 192.168.100.10/32\")")
}

func (f *databaseAddFlags) spec() database.Spec {
	return database.Spec{
		Password:     f.password,
		Comment:      f.comment,
		AllowedHosts: f.allowedHosts,
	}
}

func newDatabasesAddCmd(opts *RootOptions) *cobra.Command {
	f := &databaseAddFlags{}
	cmd := &cobra.Command{
		Use:   "add --password <pw> --comment <text> [--allowed-hosts <hosts>]",
		Short: "Create a database (add_database; the login is generated by KAS)",
		Long: `Create a database via add_database. KAS generates the login and the
command prints it on success.

--allowed-hosts is optional: an empty value (or omitting the flag) is
the KAS API's documented "any host may connect" wildcard — it is
sent on the wire as an empty database_allowed_hosts parameter, which
the API interprets as unrestricted access. Pass an explicit
comma-separated list of host names / IPs / CIDR blocks to restrict
access.`,
		Args: cobra.NoArgs,
		RunE: runWriteE(opts, func([]string) (writeSpec, error) {
			if f.password == "" {
				return writeSpec{}, fmt.Errorf("--password is required")
			}
			if f.comment == "" {
				return writeSpec{}, fmt.Errorf("--comment is required")
			}
			s := f.spec()
			var createdID string
			return writeSpec{
				action:      "add_database",
				destructive: false,
				confirm:     ConfirmAction{Verb: "create", Resource: "database", ID: f.comment},
				params:      database.AddParams(s),
				createdID:   &createdID,
				dispatch: func(c *api.Client, ctx context.Context) (string, error) {
					login, derr := database.NewClient(c).Add(ctx, s)
					if derr != nil {
						return "", derr
					}
					createdID = login
					return "created database " + login, nil
				},
			}, nil
		}),
	}
	f.bind(cmd)
	return cmd
}

// databaseUpdateFlags binds the update_database mutable surface.
// Disjoint from databaseAddFlags so update's --help describes the
// flags as replacements (not "required for add") and cobra rejects an
// add-only flag at parse time.
//
// The password flag maps to database_new_password on this subcommand
// (the update_database key) rather than the add-only
// database_password — see databaseUpdateChangedFields.
type databaseUpdateFlags struct {
	password     string
	comment      string
	allowedHosts string
}

func (f *databaseUpdateFlags) bind(cmd *cobra.Command) {
	fl := cmd.Flags()
	fl.StringVar(&f.password, "password", "", "replacement database password (sent as database_new_password)")
	fl.StringVar(&f.comment, "comment", "", "replacement comment / label")
	fl.StringVar(&f.allowedHosts, "allowed-hosts", "", "replacement comma-separated list of hosts allowed to connect")
}

// databaseUpdateChangedFields collects only the flags the user
// explicitly set into the update_database field map (keyed on the
// database.Field* constants). Each field is a wholesale replacement
// and an empty value is a meaningful set, so presence is keyed on
// cobra Changed, not on the value being non-empty — the same pattern
// the ftpuser/sambauser updates use. The password flag maps to
// database_new_password here (update_database's key) rather than the
// add-only database_password.
func databaseUpdateChangedFields(cmd *cobra.Command, f *databaseUpdateFlags) map[string]string {
	fields := map[string]string{}
	if cmd.Flags().Changed("password") {
		fields[database.FieldNewPassword] = f.password
	}
	if cmd.Flags().Changed("comment") {
		fields[database.FieldComment] = f.comment
	}
	if cmd.Flags().Changed("allowed-hosts") {
		fields[database.FieldAllowedHosts] = f.allowedHosts
	}
	return fields
}

func newDatabasesUpdateCmd(opts *RootOptions) *cobra.Command {
	f := &databaseUpdateFlags{}
	cmd := &cobra.Command{
		Use:   "update <database-login> [password/comment/allowed-hosts flags]",
		Short: "Replace mutable fields of a database (update_database)",
		Args:  cobra.ExactArgs(1),
	}
	cmd.RunE = runWriteE(opts, func(args []string) (writeSpec, error) {
		login := args[0]
		fields := databaseUpdateChangedFields(cmd, f)
		if len(fields) == 0 {
			return writeSpec{}, fmt.Errorf("at least one field flag (e.g. --password/--comment/--allowed-hosts) is required")
		}
		return writeSpec{
			action:      "update_database",
			destructive: true,
			confirm:     ConfirmAction{Verb: "replace the settings of", Resource: "database", ID: login},
			params:      database.UpdateParams(login, fields),
			dispatch: func(c *api.Client, ctx context.Context) (string, error) {
				if derr := database.NewClient(c).Update(ctx, login, fields); derr != nil {
					return "", derr
				}
				return "updated database " + login, nil
			},
		}, nil
	})
	f.bind(cmd)
	return cmd
}

// databaseDeleteConfirm builds the ConfirmAction shown before
// delete_database is dispatched. Extracted from the RunE closure so
// the loudness adjustment (Verb: "permanently delete" instead of the
// bare "delete" every other slice uses) is structurally pinned by a
// test rather than only by a source-code comment.
//
// delete_database drops the database AND every row it contains, which
// is the loudest data-loss surface of the v0.2.0 write phase. The
// prompt template adds "This cannot be undone." regardless of the
// verb.
func databaseDeleteConfirm(login string) ConfirmAction {
	return ConfirmAction{Verb: "permanently delete", Resource: "database", ID: login}
}

func newDatabasesDeleteCmd(opts *RootOptions) *cobra.Command {
	return &cobra.Command{
		Use:   "delete <database-login>",
		Short: "Permanently delete a database and all data in it (delete_database)",
		Args:  cobra.ExactArgs(1),
		RunE: runWriteE(opts, func(args []string) (writeSpec, error) {
			login := args[0]
			return writeSpec{
				action:      "delete_database",
				destructive: true,
				confirm:     databaseDeleteConfirm(login),
				params:      database.DeleteParams(login),
				dispatch: func(c *api.Client, ctx context.Context) (string, error) {
					if derr := database.NewClient(c).Delete(ctx, login); derr != nil {
						return "", derr
					}
					return "deleted database " + login, nil
				},
			}, nil
		}),
	}
}
