package cli

import (
	"context"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chmmou/kasapi-cli/internal/api"
	"github.com/chmmou/kasapi-cli/internal/ddns"
)

// NewDDNSUsersCmd returns the "kasapi-cli ddnsusers" subcommand tree:
// list/get (get_ddnsusers, list and singular) plus the add / update /
// delete write endpoints (add_ddnsuser / update_ddnsuser /
// delete_ddnsuser). update and delete are gated by the #109
// confirmation prompt; add is reversible and not prompted.
//
// The action name uses "ddnsuser" / "ddnsusers" (no `y`), the get
// filter parameter uses "ddns_login" (no `y`), but every other request
// key uses the "dyndns_*" prefix (with `y`). See the ddns.Field*
// doc-comment for the full wire-side note.
func NewDDNSUsersCmd(opts *RootOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "ddnsusers",
		Short: "Inspect and manage DDNS users (get/add/update/delete_ddnsuser)",
	}
	cmd.AddCommand(
		newDDNSUsersListCmd(opts),
		newDDNSUsersGetCmd(opts),
		newDDNSUsersAddCmd(opts),
		newDDNSUsersUpdateCmd(opts),
		newDDNSUsersDeleteCmd(opts),
	)
	return cmd
}

func newDDNSUsersListCmd(opts *RootOptions) *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List all DDNS users (get_ddnsusers, no filter)",
		Args:  cobra.NoArgs,
		RunE: runListE(opts, "get_ddnsusers", func(c *api.Client, ctx context.Context) (ddns.DDNSUserList, error) {
			return ddns.NewClient(c).List(ctx)
		}),
	}
}

func newDDNSUsersGetCmd(opts *RootOptions) *cobra.Command {
	return &cobra.Command{
		Use:   "get <ddns-login>",
		Short: "Show details for a single DDNS user (get_ddnsusers with ddns_login)",
		Args:  cobra.ExactArgs(1),
		RunE: runGetE(opts, "get_ddnsusers", func(c *api.Client, ctx context.Context, arg string) (ddns.DDNSUser, error) {
			return ddns.NewClient(c).Get(ctx, arg)
		}),
	}
}

// ddnsuserWriteFlags binds the union of add_ddnsuser / update_ddnsuser
// request fields to a command. The same flag set serves both, but the
// two actions consume different subsets:
//
//   - add reads --password/--zone/--label/--target-ip/--comment/
//     --dual-stack (legacy single-IP path).
//   - update reads only the flags the user explicitly changed
//     (see ddnsuserChangedFields), with --target-ipv4/--target-ipv6
//     replacing add's --target-ip. Those two ipv4/ipv6 keys are
//     undocumented in the KAS API but verified to work — see the
//     ddns.Field* doc-comment.
//
// The password flag maps to the same KAS key (dyndns_password) on both
// actions — there is no _new_password split here, unlike
// ftpuser/sambauser.
type ddnsuserWriteFlags struct {
	password   string
	zone       string
	label      string
	targetIP   string
	targetIPv4 string
	targetIPv6 string
	comment    string
	dualStack  bool
}

func (f *ddnsuserWriteFlags) bind(cmd *cobra.Command) {
	fl := cmd.Flags()
	fl.StringVar(&f.password, "password", "", "DDNS password (required for add; same key for update)")
	fl.StringVar(&f.zone, "zone", "", "DNS zone the record lives under (required for add)")
	fl.StringVar(&f.label, "label", "", "host label below the zone (required for add)")
	fl.StringVar(&f.targetIP, "target-ip", "", "legacy single-IP target for add_ddnsuser")
	fl.StringVar(&f.targetIPv4, "target-ipv4", "", "IPv4 target for update_ddnsuser (undocumented but verified)")
	fl.StringVar(&f.targetIPv6, "target-ipv6", "", "IPv6 target for update_ddnsuser (undocumented but verified)")
	fl.StringVar(&f.comment, "comment", "", "user comment / label (required for add)")
	fl.BoolVar(&f.dualStack, "dual-stack", false, "enable dual-stack (Y/N); off by default")
}

func (f *ddnsuserWriteFlags) spec() ddns.Spec {
	return ddns.Spec{
		Password:  f.password,
		Zone:      f.zone,
		Label:     f.label,
		TargetIP:  f.targetIP,
		Comment:   f.comment,
		DualStack: boolToYN(f.dualStack),
	}
}

func newDDNSUsersAddCmd(opts *RootOptions) *cobra.Command {
	f := &ddnsuserWriteFlags{}
	cmd := &cobra.Command{
		Use:   "add --password <pw> --zone <z> --label <l> --target-ip <ip> --comment <text> [--dual-stack]",
		Short: "Create a DDNS user (add_ddnsuser; the login is generated by KAS)",
		Args:  cobra.NoArgs,
		RunE: runWriteE(opts, func([]string) (writeSpec, error) {
			if f.password == "" {
				return writeSpec{}, fmt.Errorf("--password is required")
			}
			if f.zone == "" {
				return writeSpec{}, fmt.Errorf("--zone is required")
			}
			if f.label == "" {
				return writeSpec{}, fmt.Errorf("--label is required")
			}
			if f.targetIP == "" {
				return writeSpec{}, fmt.Errorf("--target-ip is required (add_ddnsuser uses the legacy single-IP key)")
			}
			if f.comment == "" {
				return writeSpec{}, fmt.Errorf("--comment is required")
			}
			s := f.spec()
			return writeSpec{
				action:      "add_ddnsuser",
				destructive: false,
				confirm:     ConfirmAction{Verb: "create", Resource: "ddns user", ID: f.comment},
				params:      ddns.AddParams(s),
				dispatch: func(c *api.Client, ctx context.Context) (string, error) {
					login, derr := ddns.NewClient(c).Add(ctx, s)
					if derr != nil {
						return "", derr
					}
					return "created ddns user " + login, nil
				},
			}, nil
		}),
	}
	f.bind(cmd)
	return cmd
}

// ddnsuserChangedFields collects only the write flags the user
// explicitly set into the update_ddnsuser field map (keyed on the
// ddns.Field* constants). Each field is a wholesale replacement and an
// empty value is a meaningful set, so presence is keyed on cobra
// Changed, not on the value being non-empty — the same pattern the
// ftpuser/sambauser updates use.
//
// update_ddnsuser does not accept --zone, --label or the legacy
// --target-ip: the dyndns_login identifier is immutable, and the dual-
// stack ipv4/ipv6 pair replaces the legacy single-IP key. These flags
// are still bound on the command so the help text stays unified, but
// they are deliberately ignored here.
func ddnsuserChangedFields(cmd *cobra.Command, f *ddnsuserWriteFlags) map[string]string {
	fields := map[string]string{}
	if cmd.Flags().Changed("password") {
		fields[ddns.FieldPassword] = f.password
	}
	if cmd.Flags().Changed("comment") {
		fields[ddns.FieldComment] = f.comment
	}
	if cmd.Flags().Changed("target-ipv4") {
		fields[ddns.FieldTargetIPv4] = f.targetIPv4
	}
	if cmd.Flags().Changed("target-ipv6") {
		fields[ddns.FieldTargetIPv6] = f.targetIPv6
	}
	if cmd.Flags().Changed("dual-stack") {
		fields[ddns.FieldDualStack] = boolToYN(f.dualStack)
	}
	return fields
}

func newDDNSUsersUpdateCmd(opts *RootOptions) *cobra.Command {
	f := &ddnsuserWriteFlags{}
	cmd := &cobra.Command{
		Use:   "update <dyndns-login> [password/target/dual-stack flags]",
		Short: "Replace mutable fields of a DDNS user (update_ddnsuser)",
		Args:  cobra.ExactArgs(1),
	}
	cmd.RunE = runWriteE(opts, func(args []string) (writeSpec, error) {
		login := args[0]
		fields := ddnsuserChangedFields(cmd, f)
		if len(fields) == 0 {
			return writeSpec{}, fmt.Errorf("at least one field flag (e.g. --password/--comment/--target-ipv4/--target-ipv6/--dual-stack) is required")
		}
		return writeSpec{
			action:      "update_ddnsuser",
			destructive: true,
			confirm:     ConfirmAction{Verb: "replace the settings of", Resource: "ddns user", ID: login},
			params:      ddns.UpdateParams(login, fields),
			dispatch: func(c *api.Client, ctx context.Context) (string, error) {
				if derr := ddns.NewClient(c).Update(ctx, login, fields); derr != nil {
					return "", derr
				}
				return "updated ddns user " + login, nil
			},
		}, nil
	})
	f.bind(cmd)
	return cmd
}

func newDDNSUsersDeleteCmd(opts *RootOptions) *cobra.Command {
	return &cobra.Command{
		Use:   "delete <dyndns-login>",
		Short: "Delete a DDNS user (delete_ddnsuser)",
		Args:  cobra.ExactArgs(1),
		RunE: runWriteE(opts, func(args []string) (writeSpec, error) {
			login := args[0]
			return writeSpec{
				action:      "delete_ddnsuser",
				destructive: true,
				confirm:     ConfirmAction{Verb: "delete", Resource: "ddns user", ID: login},
				params:      ddns.DeleteParams(login),
				dispatch: func(c *api.Client, ctx context.Context) (string, error) {
					if derr := ddns.NewClient(c).Delete(ctx, login); derr != nil {
						return "", derr
					}
					return "deleted ddns user " + login, nil
				},
			}, nil
		}),
	}
}
