package cli

import (
	"context"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chmmou/kasapi-cli/internal/api"
	"github.com/chmmou/kasapi-cli/internal/ftpuser"
)

// NewFTPUsersCmd returns the "kasapi-cli ftpusers" subcommand tree:
// list/get (get_ftpusers, list and singular) plus the add / update /
// delete write endpoints (add_ftpuser / update_ftpuser /
// delete_ftpuser). update and delete are gated by the #109
// confirmation prompt; add is reversible and not prompted.
func NewFTPUsersCmd(opts *RootOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "ftpusers",
		Short: "Inspect and manage FTP users (get/add/update/delete_ftpuser)",
	}
	cmd.AddCommand(
		newFTPUsersListCmd(opts),
		newFTPUsersGetCmd(opts),
		newFTPUsersAddCmd(opts),
		newFTPUsersUpdateCmd(opts),
		newFTPUsersDeleteCmd(opts),
	)
	return cmd
}

func newFTPUsersListCmd(opts *RootOptions) *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List all FTP users (get_ftpusers, no filter)",
		Args:  cobra.NoArgs,
		RunE: runListE(opts, "get_ftpusers", func(c *api.Client, ctx context.Context) (ftpuser.FTPUserList, error) {
			return ftpuser.NewClient(c).List(ctx)
		}),
	}
}

func newFTPUsersGetCmd(opts *RootOptions) *cobra.Command {
	return &cobra.Command{
		Use:   "get <ftp-login>",
		Short: "Show details for a single FTP user (get_ftpusers with ftp_login)",
		Args:  cobra.ExactArgs(1),
		RunE: runGetE(opts, "get_ftpusers", func(c *api.Client, ctx context.Context, arg string) (ftpuser.FTPUser, error) {
			return ftpuser.NewClient(c).Get(ctx, arg)
		}),
	}
}

// ftpuserWriteFlags binds the add_ftpuser request fields to a command.
// The password flag maps to the add-only ftp_password key — the update
// subcommand binds its own ftpuserUpdateFlags so its --help does not
// advertise add defaults or "required for add" texts.
type ftpuserWriteFlags struct {
	password  string
	comment   string
	path      string
	permRead  bool
	permWrite bool
	permList  bool
	virusClam bool
}

func (f *ftpuserWriteFlags) bind(cmd *cobra.Command) {
	fl := cmd.Flags()
	fl.StringVar(&f.password, "password", "", "FTP password (required)")
	fl.StringVar(&f.comment, "comment", "", "user comment / label (required)")
	fl.StringVar(&f.path, "path", "/", "home directory the user is jailed to (ftp_path)")
	fl.BoolVar(&f.permRead, "permission-read", true, "grant read access; pass --permission-read=false to deny")
	fl.BoolVar(&f.permWrite, "permission-write", true, "grant write access; pass --permission-write=false to deny")
	fl.BoolVar(&f.permList, "permission-list", true, "grant directory-list access; pass --permission-list=false to deny")
	fl.BoolVar(&f.virusClam, "virus-clamav", true, "enable ClamAV scanning; pass --virus-clamav=false to disable")
}

func (f *ftpuserWriteFlags) spec() ftpuser.Spec {
	return ftpuser.Spec{
		Password:        f.password,
		Comment:         f.comment,
		Path:            f.path,
		PermissionRead:  boolToYN(f.permRead),
		PermissionWrite: boolToYN(f.permWrite),
		PermissionList:  boolToYN(f.permList),
		VirusClamAV:     boolToYN(f.virusClam),
	}
}

func newFTPUsersAddCmd(opts *RootOptions) *cobra.Command {
	f := &ftpuserWriteFlags{}
	cmd := &cobra.Command{
		Use:   "add --password <pw> --comment <text> [flags]",
		Short: "Create an FTP user (add_ftpuser; the login is generated by KAS)",
		Args:  cobra.NoArgs,
		RunE: runWriteE(opts, func([]string) (writeSpec, error) {
			if f.password == "" {
				return writeSpec{}, fmt.Errorf("--password is required")
			}
			if f.comment == "" {
				return writeSpec{}, fmt.Errorf("--comment is required")
			}
			s := f.spec()
			return writeSpec{
				action:      "add_ftpuser",
				destructive: false,
				confirm:     ConfirmAction{Verb: "create", Resource: "ftp user", ID: f.comment},
				params:      ftpuser.AddParams(s),
				dispatch: func(c *api.Client, ctx context.Context) (string, error) {
					login, derr := ftpuser.NewClient(c).Add(ctx, s)
					if derr != nil {
						return "", derr
					}
					return "created ftp user " + login, nil
				},
			}, nil
		}),
	}
	f.bind(cmd)
	return cmd
}

// ftpuserUpdateFlags binds the update_ftpuser mutable surface.
// Disjoint from ftpuserWriteFlags so update's --help describes the
// flags as replacements (not "required for add") and does not
// advertise add defaults that update never sends — the same split the
// database/mailaccount/ddnsuser/mailinglist slices use.
//
// The password flag maps to ftp_new_password on this subcommand (the
// update_ftpuser key) rather than the add-only ftp_password — see
// ftpuserChangedFields.
type ftpuserUpdateFlags struct {
	password  string
	comment   string
	path      string
	permRead  bool
	permWrite bool
	permList  bool
	virusClam bool
}

func (f *ftpuserUpdateFlags) bind(cmd *cobra.Command) {
	fl := cmd.Flags()
	fl.StringVar(&f.password, "password", "", "replacement FTP password (sent as ftp_new_password)")
	fl.StringVar(&f.comment, "comment", "", "replacement user comment / label")
	fl.StringVar(&f.path, "path", "", "replacement home directory the user is jailed to (ftp_path)")
	fl.BoolVar(&f.permRead, "permission-read", true, "replacement read access; pass --permission-read=false to deny")
	fl.BoolVar(&f.permWrite, "permission-write", true, "replacement write access; pass --permission-write=false to deny")
	fl.BoolVar(&f.permList, "permission-list", true, "replacement directory-list access; pass --permission-list=false to deny")
	fl.BoolVar(&f.virusClam, "virus-clamav", true, "replacement ClamAV scanning; pass --virus-clamav=false to disable")
}

// ftpuserChangedFields collects only the write flags the user
// explicitly set into the update_ftpuser field map (keyed on the
// ftpuser.Field* constants). Each field is a wholesale replacement and
// an empty value is a meaningful set, so presence is keyed on cobra
// Changed, not on the value being non-empty — the same pattern the
// cronjob update uses. The password flag maps to ftp_new_password here
// (update_ftpuser's key) rather than the add-only ftp_password.
func ftpuserChangedFields(cmd *cobra.Command, f *ftpuserUpdateFlags) map[string]string {
	fields := map[string]string{}
	if cmd.Flags().Changed("password") {
		fields[ftpuser.FieldNewPassword] = f.password
	}
	if cmd.Flags().Changed("comment") {
		fields[ftpuser.FieldComment] = f.comment
	}
	if cmd.Flags().Changed("path") {
		fields[ftpuser.FieldPath] = f.path
	}
	// flag name -> {KAS request key, Y/N value} for the boolean flags.
	for flag, kv := range map[string][2]string{
		"permission-read":  {ftpuser.FieldPermissionRead, boolToYN(f.permRead)},
		"permission-write": {ftpuser.FieldPermissionWrite, boolToYN(f.permWrite)},
		"permission-list":  {ftpuser.FieldPermissionList, boolToYN(f.permList)},
		"virus-clamav":     {ftpuser.FieldVirusClamAV, boolToYN(f.virusClam)},
	} {
		if cmd.Flags().Changed(flag) {
			fields[kv[0]] = kv[1]
		}
	}
	return fields
}

func newFTPUsersUpdateCmd(opts *RootOptions) *cobra.Command {
	f := &ftpuserUpdateFlags{}
	cmd := &cobra.Command{
		Use:   "update <ftp-login> [password/permission flags]",
		Short: "Replace mutable fields of an FTP user (update_ftpuser)",
		Args:  cobra.ExactArgs(1),
	}
	cmd.RunE = runWriteE(opts, func(args []string) (writeSpec, error) {
		login := args[0]
		fields := ftpuserChangedFields(cmd, f)
		if len(fields) == 0 {
			return writeSpec{}, fmt.Errorf("at least one field flag (e.g. --password/--comment/--permission-read) is required")
		}
		return writeSpec{
			action:      "update_ftpuser",
			destructive: true,
			confirm:     ConfirmAction{Verb: "replace the settings of", Resource: "ftp user", ID: login},
			params:      ftpuser.UpdateParams(login, fields),
			dispatch: func(c *api.Client, ctx context.Context) (string, error) {
				if derr := ftpuser.NewClient(c).Update(ctx, login, fields); derr != nil {
					return "", derr
				}
				return "updated ftp user " + login, nil
			},
		}, nil
	})
	f.bind(cmd)
	return cmd
}

func newFTPUsersDeleteCmd(opts *RootOptions) *cobra.Command {
	return &cobra.Command{
		Use:   "delete <ftp-login>",
		Short: "Delete an FTP user (delete_ftpuser)",
		Args:  cobra.ExactArgs(1),
		RunE: runWriteE(opts, func(args []string) (writeSpec, error) {
			login := args[0]
			return writeSpec{
				action:      "delete_ftpuser",
				destructive: true,
				confirm:     ConfirmAction{Verb: "delete", Resource: "ftp user", ID: login},
				params:      ftpuser.DeleteParams(login),
				dispatch: func(c *api.Client, ctx context.Context) (string, error) {
					if derr := ftpuser.NewClient(c).Delete(ctx, login); derr != nil {
						return "", derr
					}
					return "deleted ftp user " + login, nil
				},
			}, nil
		}),
	}
}
