package cli_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/chmmou/kasapi-cli/internal/cli"
)

// TestGenDocsWritesMarkdownTree exercises the same path `make docs` uses:
// attach gen-docs to the real root and have it walk the assembled command
// tree into a temp dir. It guards the build-time helper that keeps
// docs/cli/ in sync with the CLI surface.
func TestGenDocsWritesMarkdownTree(t *testing.T) {
	t.Parallel()
	root, _ := cli.NewRootCmd()
	root.AddCommand(cli.NewGenDocsCmd())

	out := t.TempDir()
	root.SetArgs([]string{"gen-docs", out})
	if err := root.Execute(); err != nil {
		t.Fatalf("Execute: %v", err)
	}

	rootDoc := filepath.Join(out, "kasapi-cli.md")
	//nolint:gosec // G304: rootDoc is filepath.Join(t.TempDir(), constant); no external input.
	b, err := os.ReadFile(rootDoc)
	if err != nil {
		t.Fatalf("expected %s to be written: %v", rootDoc, err)
	}
	if len(b) == 0 {
		t.Errorf("%s is empty", rootDoc)
	}
	// DisableAutoGenTag must be honoured so `make docs` output is
	// reproducible (no per-run timestamp churn).
	if strings.Contains(string(b), "Auto generated by spf13/cobra") {
		t.Errorf("%s carries an auto-gen timestamp tag; output is not reproducible", rootDoc)
	}
}

func TestGenDocsRequiresOutDirArg(t *testing.T) {
	t.Parallel()
	root, _ := cli.NewRootCmd()
	root.AddCommand(cli.NewGenDocsCmd())

	var buf bytes.Buffer
	root.SetOut(&buf)
	root.SetErr(&buf)
	root.SetArgs([]string{"gen-docs"})
	if err := root.Execute(); err == nil {
		t.Fatal("Execute returned nil, want error for missing <out-dir> argument")
	}
}
