package cli

import (
	"context"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/chmmou/kasapi-cli/internal/api"
	"github.com/chmmou/kasapi-cli/internal/sambauser"
)

// NewSambaUsersCmd returns the "kasapi-cli sambausers" subcommand
// tree: list/get (get_sambausers, list and singular) plus the add /
// update / delete write endpoints (add_sambauser / update_sambauser /
// delete_sambauser). update and delete are gated by the #109
// confirmation prompt; add is reversible and not prompted.
func NewSambaUsersCmd(opts *RootOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "sambausers",
		Short: "Inspect and manage Samba/CIFS users (get/add/update/delete_sambauser)",
	}
	cmd.AddCommand(
		newSambaUsersListCmd(opts),
		newSambaUsersGetCmd(opts),
		newSambaUsersAddCmd(opts),
		newSambaUsersUpdateCmd(opts),
		newSambaUsersDeleteCmd(opts),
	)
	return cmd
}

func newSambaUsersListCmd(opts *RootOptions) *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List all Samba users (get_sambausers, no filter)",
		Args:  cobra.NoArgs,
		RunE: runListE(opts, "get_sambausers", func(c *api.Client, ctx context.Context) (sambauser.SambaUserList, error) {
			return sambauser.NewClient(c).List(ctx)
		}),
	}
}

func newSambaUsersGetCmd(opts *RootOptions) *cobra.Command {
	return &cobra.Command{
		Use:   "get <samba-login>",
		Short: "Show details for a single Samba user (get_sambausers with samba_login)",
		Args:  cobra.ExactArgs(1),
		RunE: runGetE(opts, "get_sambausers", func(c *api.Client, ctx context.Context, arg string) (sambauser.SambaUser, error) {
			return sambauser.NewClient(c).Get(ctx, arg)
		}),
	}
}

// sambauserWriteFlags binds the shared add_sambauser / update_sambauser
// request fields to a command. The same flag set serves both: add
// reads every value, update sends only the flags the user explicitly
// changed (see sambauserChangedFields). The password flag maps to a
// different KAS key per action (add_sambauser: samba_password,
// update_sambauser: samba_new_password) — see spec() and
// sambauserChangedFields.
type sambauserWriteFlags struct {
	password string
	comment  string
	path     string
}

func (f *sambauserWriteFlags) bind(cmd *cobra.Command) {
	fl := cmd.Flags()
	fl.StringVar(&f.password, "password", "", "Samba password (required for add; new password for update)")
	fl.StringVar(&f.comment, "comment", "", "user comment / label (required for add)")
	fl.StringVar(&f.path, "path", "", "share path the user is granted (samba_path; required for add)")
}

func (f *sambauserWriteFlags) spec() sambauser.Spec {
	return sambauser.Spec{
		Password: f.password,
		Comment:  f.comment,
		Path:     f.path,
	}
}

func newSambaUsersAddCmd(opts *RootOptions) *cobra.Command {
	f := &sambauserWriteFlags{}
	cmd := &cobra.Command{
		Use:   "add --password <pw> --comment <text> --path <p>",
		Short: "Create a Samba user (add_sambauser; the login is generated by KAS)",
		Args:  cobra.NoArgs,
		RunE: runWriteE(opts, func([]string) (writeSpec, error) {
			if f.password == "" {
				return writeSpec{}, fmt.Errorf("--password is required")
			}
			if f.comment == "" {
				return writeSpec{}, fmt.Errorf("--comment is required")
			}
			if f.path == "" {
				return writeSpec{}, fmt.Errorf("--path is required")
			}
			s := f.spec()
			return writeSpec{
				action:      "add_sambauser",
				destructive: false,
				confirm:     ConfirmAction{Verb: "create", Resource: "samba user", ID: f.comment},
				params:      sambauser.AddParams(s),
				dispatch: func(c *api.Client, ctx context.Context) (string, error) {
					login, derr := sambauser.NewClient(c).Add(ctx, s)
					if derr != nil {
						return "", derr
					}
					return "created samba user " + login, nil
				},
			}, nil
		}),
	}
	f.bind(cmd)
	return cmd
}

// sambauserChangedFields collects only the write flags the user
// explicitly set into the update_sambauser field map (keyed on the
// sambauser.Field* constants). Each field is a wholesale replacement
// and an empty value is a meaningful set, so presence is keyed on cobra
// Changed, not on the value being non-empty — the same pattern the
// ftpuser update uses. The password flag maps to samba_new_password
// here (update_sambauser's key) rather than the add-only
// samba_password.
func sambauserChangedFields(cmd *cobra.Command, f *sambauserWriteFlags) map[string]string {
	fields := map[string]string{}
	if cmd.Flags().Changed("password") {
		fields[sambauser.FieldNewPassword] = f.password
	}
	if cmd.Flags().Changed("comment") {
		fields[sambauser.FieldComment] = f.comment
	}
	if cmd.Flags().Changed("path") {
		fields[sambauser.FieldPath] = f.path
	}
	return fields
}

func newSambaUsersUpdateCmd(opts *RootOptions) *cobra.Command {
	f := &sambauserWriteFlags{}
	cmd := &cobra.Command{
		Use:   "update <samba-login> [password/path flags]",
		Short: "Replace mutable fields of a Samba user (update_sambauser)",
		Args:  cobra.ExactArgs(1),
	}
	cmd.RunE = runWriteE(opts, func(args []string) (writeSpec, error) {
		login := args[0]
		fields := sambauserChangedFields(cmd, f)
		if len(fields) == 0 {
			return writeSpec{}, fmt.Errorf("at least one field flag (e.g. --password/--comment/--path) is required")
		}
		return writeSpec{
			action:      "update_sambauser",
			destructive: true,
			confirm:     ConfirmAction{Verb: "replace the settings of", Resource: "samba user", ID: login},
			params:      sambauser.UpdateParams(login, fields),
			dispatch: func(c *api.Client, ctx context.Context) (string, error) {
				if derr := sambauser.NewClient(c).Update(ctx, login, fields); derr != nil {
					return "", derr
				}
				return "updated samba user " + login, nil
			},
		}, nil
	})
	f.bind(cmd)
	return cmd
}

func newSambaUsersDeleteCmd(opts *RootOptions) *cobra.Command {
	return &cobra.Command{
		Use:   "delete <samba-login>",
		Short: "Delete a Samba user (delete_sambauser)",
		Args:  cobra.ExactArgs(1),
		RunE: runWriteE(opts, func(args []string) (writeSpec, error) {
			login := args[0]
			return writeSpec{
				action:      "delete_sambauser",
				destructive: true,
				confirm:     ConfirmAction{Verb: "delete", Resource: "samba user", ID: login},
				params:      sambauser.DeleteParams(login),
				dispatch: func(c *api.Client, ctx context.Context) (string, error) {
					if derr := sambauser.NewClient(c).Delete(ctx, login); derr != nil {
						return "", derr
					}
					return "deleted samba user " + login, nil
				},
			}, nil
		}),
	}
}
